### ISSUE TITLE
Mismatch Property 

### ISSUE THREAD

**Issue by MuazAshraf** [getzep/graphiti#86] opened 2024-09-05 17:39 UTC
Neo4J has name_embedding property but when I add the name_embedding property with the graphit it gave me this warning or error

Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: name_embeddings)} {position: line: 7, column: 23, offset: 249} for query: '\n                CALL db.index.vector.queryNodes("name_embedding", $limit, $search_vector)\n                YIELD node AS n, score\n                RETURN\n                    n.uuid As uuid, \n                    n.name AS name, \n                    n.name_embeddings AS name_embedding,\n                    n.created_at AS created_at, \n                    n.summary AS summary\n                ORDER BY score DESC\n                '
Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: name_embeddings)} {position: line: 6, column: 14, offset: 165} for query: '\n    CALL db.index.fulltext.queryNodes("name_and_summary", $query) YIELD node, score\n    RETURN\n        node.uuid AS uuid, \n        node.name AS name, \n        node.name_embeddings AS name_embedding,\n        node.created_at AS created_at, \n        node.summary AS summary\n    ORDER BY score DESC\n    LIMIT $limit\n    '

**Comment by prasmussen15** [comment] 2024-09-05 18:26
Hey! Thanks for the report. This issue was caused by us inadvertently clearing `name_embeddings` during node updates. We have a fix for this in our latest patch release (0.2.2). Unfortunately, this won't restore `name_embeddings` that have been cleared.

If you have a small number of episodes ingested you can fix the issue by clearing your graphDB and then rerunning add_episode on your episodes. If that is not an option for you you can run this query:
`MATCH (n:Entity{name_embedding: NULL}) RETURN n`
Through the neo4j driver to get all effected uuids. Then you can use EntityNode.get_by_uuid() to get the effected entityNode objects. After that you can run entityNode.generate_name_embedding() and entityNode.save() on each of the entityNode objects to fix the issue.

I apologize for the inconvenience.

**Closed by prasmussen15** 2024-09-05 18:26 UTC

**Comment by yukiman76** [comment] 2024-09-13 20:25
This might still be an issue, ref https://github.com/getzep/graphiti/issues/109
